; Listing generated by Microsoft (R) Optimizing Compiler Version 19.39.33523.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__7BF42827_EndBrace@h DB 01H
__FFB2486C_Math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?add_@@YAHHH@Z					; add_
PUBLIC	__JustMyCode_Default
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?add_@@YAHHH@Z DD imagerel $LN4
	DD	imagerel $LN4+40
	DD	imagerel $unwind$?add_@@YAHHH@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?add_@@YAHHH@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?add_@@YAHHH@Z
_TEXT	SEGMENT
c$ = 48
d$ = 56
?add_@@YAHHH@Z PROC					; add_, COMDAT
; File D:\Code Files\C++\VS\HelloWorld\Math.cpp
; Line 13
$LN4:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	ebx, ecx
	mov	edi, edx
; File D:\Code Files\C++\VS\HelloWorld\EndBrace.h
	lea	rcx, OFFSET FLAT:__7BF42827_EndBrace@h
	call	__CheckForDebuggerJustMyCode
	lea	eax, DWORD PTR [rbx+rdi]
	mov	rbx, QWORD PTR [rsp+48]
; Line 1
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?add_@@YAHHH@Z ENDP					; add_
_TEXT	ENDS
END
